// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://badvvskmnfzuichrwzhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhZHZ2c2ttbmZ6dWljaHJ3emhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NDE2NDQsImV4cCI6MjA2MTAxNzY0NH0.TOLfY1pf1hzCXrLVoN8s7eGHLOc8M_YNlBdx34HQ6QM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);